# Generated by Django 3.0.6 on 2020-06-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200601_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ciudad',
            new_name='municipio',
        ),
    ]
