# Generated by Django 3.0.6 on 2020-06-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200601_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='foto',
        ),
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='users/pictures/', verbose_name='foto de perfil'),
        ),
    ]
