# Generated by Django 3.0.6 on 2020-05-31 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=60)),
                ('num_cedula', models.CharField(max_length=20)),
                ('mesa', models.CharField(max_length=4)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locaciones.Barrio')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('puesto_votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locaciones.PuestoVotacion')),
            ],
            options={
                'ordering': ['-creado', '-modificado'],
                'get_latest_by': 'creado',
                'abstract': False,
            },
        ),
    ]
